
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('companies').del()
    .then(function () {
      // Inserts seed entries
      // ALL INFORMATION BELOW WAS COMPILED THROUGH PUBLICALLY AVAILABLE INFORMATION
      return knex('companies').insert([
        { id: 1, 
          label: 'panda',
          name: 'Kin', 
          description: 'A member of the g79 Cohort of Galvanize. His hobbies include traveling, being a foodie, along with consuming copious amounts of articles, literature, and books.', 
          image:'http://thestorydragon.com/wp-content/uploads/2016/02/06.png',
          website:'',
          facebook:'',
          twitter:'',
          linkedin:'https://www.linkedin.com/in/kin-siu'
        },
        { id: 2, 
          label: 'galvanize',
          name: 'Galvanize', 
          description: 'Galvanize is a community bridging the longstanding gap of industry and education by bringing industry partners, ambitious students, and education under one roof.', 
          image:'https://pbs.twimg.com/profile_images/880512924766175232/epZ-lhXw_400x400.jpg',
          website:'https://www.galvanize.com/new-york',
          facebook:'https://www.facebook.com/GalvanizeHQ',
          twitter:'https://twitter.com/galvanize',
          linkedin:'https://www.linkedin.com/company/galvanize-nyc/'
        },
        { id: 3, 
          label: 'gowatchit',
          name: 'Gowatchit', 
          description: 'GoWatchIt is your universal social discovery, bookmarking, and alert notification system; allowing you to easily find, share, save, and receive automated alerts about movies and films, from its announcement through to its availability.', 
          image:'https://pbs.twimg.com/profile_images/735170208818696192/7r1AgoYy_400x400.jpg',
          website:'https://plexusentertainment.com/',
          facebook:'https://www.facebook.com/GoWatchIt/',
          twitter:'https://twitter.com/gowatchit',
          linkedin:'https://www.linkedin.com/company/plexus-entertainment-llc---gowatchit-com/'
        },
        { id: 4, 
          label: 'designgroupitalia',
          name: 'Design Group Italia', 
          description: 'A design and branding firm specializing in creating value for companies through design-powered innovation.', 
          image:'https://pbs.twimg.com/profile_images/981088167498567680/p6svkMlp_400x400.jpg',
          website:'https://www.designgroupitalia.com/',
          facebook:'https://www.facebook.com/DesignGroupItalia',
          twitter:'https://twitter.com/designgroupit',
          linkedin:'https://www.linkedin.com/company/designgroupitalia/'
        },
        { id: 5, 
          label: 'invesco',
          name: 'Invesco', 
          description: 'Invesco is an independent investment management firm dedicated to delivering an investment experience that helps people get more out of life.', 
          image:'https://pbs.twimg.com/profile_images/466410402205544448/45nEG_6v_400x400.jpeg',
          website:'http://www.invesco.com/corporate',
          facebook:'https://www.facebook.com/InvescoUS',
          twitter:'https://twitter.com/InvescoUS',
          linkedin:'https://www.linkedin.com/company/invesco-us/'
        },
        { id: 6, 
          label: 'eulerity',
          name: 'Eulerity', 
          description: 'We are a dynamic ML/AI focused startup looking to disrupting the Ad Tech space by designing a novel product which has the potential to serve a huge market. Below is our founding team.', 
          image:'https://pbs.twimg.com/profile_images/1008821183108640768/Dlf3XmOR.jpg',
          website:'https://www.eulerity.com/',
          facebook:'https://www.facebook.com/eulerity/',
          twitter:'https://twitter.com/Eulerity',
          linkedin:'https://www.linkedin.com/company/eulerity/'
        },
        { id: 7, 
          label: 'yumble',
          name: 'Yumble Kids', 
          description: 'Yumble is a weekly subscription that delivers fresh, fully-cooked, healthy kids dinners, lunches and snacks straight to the doors of busy parents.', 
          image:'https://pbs.twimg.com/profile_images/997678731991965696/0Q_BAyNv_400x400.jpg',
          website:'https://yumblekids.com/',
          facebook:'https://www.facebook.com/yumblekids/',
          twitter:'https://twitter.com/yumblekids',
          linkedin:'https://www.linkedin.com/company/yumble/'
        },
        { id: 8, 
          label: 'swag.com',
          name: 'Swag.com', 
          description: 'Swag.com helps companies create quality promotional products that people actually want to keep. We work with 1000s of companies including Facebook and Google', 
          image:'https://www.industriousoffice.com/wp-content/uploads/2017/08/swag.png',
          website:'https://swag.com/',
          facebook:'https://www.facebook.com/promotewithswag/',
          twitter:'',
          linkedin:'https://www.linkedin.com/company/swag.com/'
        },
        { id: 9, 
          label: 'eden',
          name: 'Eden', 
          description: 'The top-rated office cleaning, IT support, handymen, and more to make it easy to run your workplace.', 
          image:'https://pbs.twimg.com/profile_images/549216399990595584/ZFUUEqC1_400x400.png',
          website:'https://www.eden.io/',
          facebook:'https://www.facebook.com/edenofficemagic',
          twitter:'https://twitter.com/edenofficemagic',
          linkedin:'https://www.linkedin.com/company/eden-inc-/'
        },
        { id: 10, 
          label: 'sendgrid',
          name: 'SendGrid', 
          description: 'Mail delivery. Simplified', 
          image:'https://pbs.twimg.com/profile_images/1013810799347814401/Qm4aPvEh_400x400.jpg',
          website:'https://sendgrid.com/',
          facebook:'https://www.facebook.com/SendGrid',
          twitter:'https://twitter.com/SendGrid',
          linkedin:'https://www.linkedin.com/company/sendgrid/'
        },
        { id: 11, 
          label: 'ibmcloud',
          name: 'IBM', 
          description: 'IBM Cloud has the tools, data and APIs to make AI real today. It’s your cloud. We protect it. You control it. Page managed by Liz Klipp and Teri Chackel. Follows IBM Social Computing Guidelines.', 
          image:'https://pbs.twimg.com/profile_images/925367546471223296/t0eKqcyC_400x400.jpg',
          website:'https://www.ibm.com/cloud/',
          facebook:'https://www.facebook.com/IBMCloud/',
          twitter:'https://twitter.com/IBMcloud',
          linkedin:'https://www.linkedin.com/showcase/ibm-cloud/'
        },
        { id: 12, 
          label: 'steppechange',
          name: 'SteppeChange', 
          description: 'We put data to work to uncover patterns and insights hidden in massive data sets.', 
          image:'https://pbs.twimg.com/profile_images/744899043097214977/YrMm-r1X_400x400.jpg',
          website:'http://steppechange.com/',
          facebook:'https://www.facebook.com/steppechange/',
          twitter:'https://twitter.com/SteppeChange',
          linkedin:'https://www.linkedin.com/company/steppechange/'
        },
        { id: 13, 
          label: 'universityventures',
          name: 'University Ventures', 
          description: 'UV is reimagining the future of higher education and creating new pathways from education to employment. UV portfolio companies are making higher education more affordable, pioneering entirely new approaches to learning, and helping employers think differently about how and where they discover talent.', 
          image:'https://pbs.twimg.com/profile_images/1860568663/UVtwitter_400x400.jpg',
          website:'http://universityventures.com/',
          facebook:'https://www.facebook.com/UniversityVenturesFund',
          twitter:'https://twitter.com/UniVenturesFund',
          linkedin:'https://www.linkedin.com/company/university-ventures/'
        },
        { id: 14, 
          label: '7miles',
          name: '7Miles Global', 
          description: 'Together we are a group of like minded entrepreneurs providing solutions for talent management, business affairs, rights management, trafficking and distribution making the impossible possible', 
          image:'https://s3-us-west-2.amazonaws.com/quilt-production/companies/2018/6/SvJiFnD-s1SIk98nVL.png',
          website:'https://www.7milesglobal.com/',
          facebook:'https://www.facebook.com/pages/biz/local-new-york/7Miles-Global-1310335062311020/',
          twitter:'https://twitter.com/marketing7miles',
          linkedin:'https://www.linkedin.com/company/7miles-global/'
        },
        { id: 15, 
          label: 'cedrus',
          name: 'Cedrus', 
          description: 'We are a boutique consulting firm that delivers digital transformation solutions, tools, and services to companies looking to accelerate their move to a cloud-centric world.', 
          image:'https://pbs.twimg.com/profile_images/852697839654273024/5_JneJTt_400x400.jpg',
          website:'http://www.cedrusco.com/',
          facebook:'https://www.facebook.com/CedrusDigital/',
          twitter:'https://twitter.com/cedrusdigital',
          linkedin:'https://www.linkedin.com/company/cedrusco/'
        },
        { id: 16, 
          label: 'perceptivethings',
          name: 'Perceptive Things', 
          description: 'Perceptive Things protects residential properties from damaging incidents, such as water leaks, via wireless battery-powered sensors installed within apartments. The sensors trigger instant notifications to property managers and tenants, expediting response times to mitigate damage and eliminate losses.', 
          image:'https://pbs.twimg.com/profile_images/875833704542748672/dn-1CaTN_400x400.jpg',
          website:'https://www.perceptivethings.com/',
          facebook:'https://www.facebook.com/perceptivethings/',
          twitter:'https://twitter.com/perceptivethngs',
          linkedin:'https://www.linkedin.com/company/perceptive-things/'
        },
        { id: 17, 
          label: 'techstars',
          name: 'Techstars', 
          description: 'Techstars helps entrepreneurs succeed. Through the Techstars Worldwide Entrepreneur Network, founders and their teams connect with other entrepreneurs, experts, mentors, alumni, investors, community leaders, and corporate partners who will help their companies grow.', 
          image:'https://pbs.twimg.com/profile_images/879467373060775936/3EewJx7o_400x400.jpg',
          website:'https://www.techstars.com/',
          facebook:'https://www.facebook.com/techstars/',
          twitter:'https://twitter.com/techstars',
          linkedin:'https://www.linkedin.com/company/techstars/'
        },
        { id: 18, 
          label: 'people\'stelevision',
          name: 'People\'s Television', 
          description: 'People’s Television is a full-service creative studio based in New York City and Washington, DC.  We create video content and digital campaigns for organizations ranging from Fortune 100 companies to grassroots non-profits, as well as award-winning feature films and documentaries.', 
          image:'https://pbs.twimg.com/profile_images/818591119797719041/yY9v4EdM_400x400.jpg',
          website:'http://peoples.tv/',
          facebook:'https://www.facebook.com/pplstv/',
          twitter:'https://twitter.com/peoplestv',
          linkedin:''
        },
        { id: 19, 
          label: 'instadat',
          name: '</INSTADAT_', 
          description: 'Instadat is a AI company focused on developing groundbreaking technology that can provide accurate and malleable predictive analytics.', 
          image:'https://scontent-lga3-1.xx.fbcdn.net/v/t1.0-1/c30.0.320.320/p320x320/11102998_712875725490025_8700155764746798371_n.png?_nc_cat=0&oh=4910239fea92d1d90923c802ddb0a2ba&oe=5BE7C03D',
          website:'http://instadat.co/',
          facebook:'https://www.facebook.com/Instadat/',
          twitter:'',
          linkedin:'https://www.linkedin.com/in/georgekailas/'
        },
        { id: 20, 
          label: 'anaconda',
          name: 'Anaconda', 
          description: 'With over 6 million users, Anaconda is the world’s most popular Python data science platform. Anaconda, Inc. continues to lead open source projects like Anaconda, NumPy, and SciPy that form the foundation of modern data science. Anaconda’s flagship product, Anaconda Enterprise, allows organizations to secure, govern, scale and extend Anaconda to deliver actionable insights that drive businesses and industries forward.', 
          image:'https://pbs.twimg.com/profile_images/1013865232945405952/oAZhGwc__400x400.jpg',
          website:'https://anaconda.org/',
          facebook:'https://www.facebook.com/anacondainc/',
          twitter:'https://twitter.com/anacondainc',
          linkedin:'https://www.linkedin.com/company/anacondainc/'
        },
        { id: 21, 
          label: 'wanderingbear',
          name: 'Wandering Bear Coffee', 
          description: 'Created cold brew coffee modeled after our favorite coffee shops around New York City. The boxes (with a tap!) eliminates air and light: the two things that makes coffee go stale.', 
          image:'https://pbs.twimg.com/profile_images/476096813762883587/SpSEUsTE_400x400.jpeg',
          website:'https://wanderingbearcoffee.com/',
          facebook:'https://www.facebook.com/wanderingbearco',
          twitter:'https://twitter.com/WanderingBearCo',
          linkedin:'https://www.linkedin.com/company/wandering-bear-coffee-co-/'
        },
        { id: 22, 
          label: 'bfv',
          name: 'Brand Foundry Ventures', 
          description: 'A Consumer focused Venture Capital firm collaborating with visionaries to build brands that scale with purpose.', 
          image:'https://pbs.twimg.com/profile_images/463798296721358849/7CW7HOCC_400x400.png',
          website:'http://brandfoundryvc.com/',
          facebook:'https://www.facebook.com/BrandFoundryVentures/',
          twitter:'https://twitter.com/BrandFoundryVC',
          linkedin:'https://www.linkedin.com/company/brand-foundry-ventures/'
        },
        { id: 23, 
          label: 'bevi',
          name: 'Bevi', 
          description: 'Our mission is to turn back the hands of time (sort of) and eliminate waste from the production, shipping, and disposing of bottled beverages. We envision a future where a smarter platform (powered by the municipal water supply) transforms how beverages are delivered. It is an ambitious goal, but we are on it!', 
          image:'https://pbs.twimg.com/profile_images/555502002617057280/746D5x44_400x400.png',
          website:'https://www.bevi.co/',
          facebook:'https://www.facebook.com/getBevi/',
          twitter:'https://twitter.com/getBevi',
          linkedin:'https://www.linkedin.com/company/bevi/'
        },
        { id: 24, 
          label: '1-800-flowers',
          name: '1-800-Flowers', 
          description: 'For over 40 years, we’ve been your destination for truly original flowers & gifts. Let us arrange a smile for you today!', 
          image:'https://pbs.twimg.com/profile_images/922528600477315072/Xq8pgrhY_400x400.jpg',
          website:'https://www.1800flowers.com/',
          facebook:'https://www.facebook.com/1800flowers',
          twitter:'https://twitter.com/1800flowers',
          linkedin:'https://www.linkedin.com/company/1800flowers-com/'
        },
        { id: 25, 
          label: 'bolt',
          name: 'Bolt Learning', 
          description: 'Bolt is an adaptive learning company, focused on helping students unlock their own potential by improving access to high quality, affordable test prep.', 
          image:'https://pbs.twimg.com/profile_images/965067458590773250/CUCn66eI_400x400.jpg',
          website:'https://www.learnwithbolt.com/',
          facebook:'https://www.facebook.com/learnwithbolt/',
          twitter:'https://twitter.com/learnwithbolt',
          linkedin:'https://www.linkedin.com/company/bolt-learning/'
        },
        { id: 26, 
          label: 'edgeworthbox',
          name: 'EdgeworthBox, Inc.', 
          description: 'EdgeworthBox makes sourcing simpler, fairer and faster.  Leveraging the experience of financial markets, we have built a marketplace for sourcing that is differentiated by a layer of additional functionality in three buckets: an administrative clearinghouse that consolidates paperwork; a transparent database of historical RFP activity including pricing; and social networking, including messaging.', 
          image:'https://pbs.twimg.com/profile_images/944268507398787073/BSENharM_400x400.jpg',
          website:'https://www.edgeworthbox.com/',
          facebook:'',
          twitter:'https://twitter.com/EdgeworthBoxInc',
          linkedin:'https://www.linkedin.com/company/edgeworthbox/'
        },
        { id: 27, 
          label: 'mymoneymyfuture',
          name: 'My Money My Future (Mi Dinero Mi Futuro) Inc.', 
          description: 'My Money My Future (MDMF) is a comprehensive financial web platform and curated newsletter dedicated to empowering millennials of color to manage their money with confidence and build wealth in their communities. MDMFâ€™s culturally unique approach makes financial matters personal, accessible, and applicable for millions of millennials just like you.', 
          image:'https://s3-us-west-2.amazonaws.com/quilt-production/companies/2016/7/8ThcrMvFl1mGZNLLAo.png',
          website:'https://mymoneymyfuture.co/',
          facebook:'https://www.facebook.com/mymoneymyfuture/',
          twitter:'https://twitter.com/mmoneymfuture',
          linkedin:'https://www.linkedin.com/company/mymoneymyfuture/'
        },
        { id: 28, 
          label: 'hubspire',
          name: 'HubSpire', 
          description: 'HubSpire is an innovative team of engineers, developers and technology experts. We specialize in mobile application development, web development, data visualization and analytics, Internet of Things (IoT) development and end-to-end IT strategy and consulting for development projects. We work with small businesses and startups, government agencies and large corporations to build people-centered tech solutions that use the full capabilities of technology.', 
          image:'https://pbs.twimg.com/profile_images/476720909126877184/LDE8Qh69_400x400.png',
          website:'https://www.hubspire.com/',
          facebook:'https://www.facebook.com/HubSpire/',
          twitter:'https://twitter.com/hubspire',
          linkedin:'https://www.linkedin.com/company/hubspire/?originalSubdomain=in'
        },
        { id: 29, 
          label: 'catchandrelease',
          name: 'Catch and Release', 
          description: 'Catch&Release partners with agencies, brands and production companies to discover user-generated, accessible and unrepresented content that meets the ever-increasing demand for authentic, ephemeral, relevant, emotional and affordable content.', 
          image:'https://pbs.twimg.com/profile_images/1007717297098665984/NqCs3-8M_400x400.jpg',
          website:'https://catchandrelease.com/',
          facebook:'https://www.facebook.com/catchandreleaseinc',
          twitter:'https://twitter.com/catchreleaseinc',
          linkedin:'https://www.linkedin.com/company/catchandrelease/'
        },
        { id: 30, 
          label: 'geopipe',
          name: 'geopipe', 
          description: 'Geopipe automatically generates detailed, expansive virtual models of the real world from data.', 
          image:'https://pbs.twimg.com/profile_images/848369615789051904/z5_ivXrK_400x400.jpg',
          website:'https://geopi.pe/',
          facebook:'https://www.facebook.com/geopipeinc',
          twitter:'https://twitter.com/geopipeinc',
          linkedin:'https://www.linkedin.com/company/geopipe-inc./'
        },
        { id: 31, 
          label: 'tetrascapital',
          name: 'Tetras Capital', 
          description: 'Tetras  Capital  is  a  New  York  City  based  hedge  fund  focused  on  the  emerging  and  rapidly  evolving  blockchain and crypto  asset  class.', 
          image:'https://pbs.twimg.com/profile_images/923038170358231041/E2cIuUEE_400x400.jpg',
          website:'http://tetras.capital/',
          facebook:'',
          twitter:'https://twitter.com/tetrascapital',
          linkedin:'https://www.linkedin.com/company/tetras-capital/'
        },
        { id: 32, 
          label: 'impact',
          name: 'Impact USA', 
          description: 'Impact is the new name for ubi i/o, the acceleration program launched by Business France and Bpifrance in 2014 in San Francisco. Our vision has always been to build a global platform for French startups that have the ambition to become global.', 
          image:'https://pbs.twimg.com/profile_images/1016394730156912640/fV8YDSvq_400x400.jpg',
          website:'http://www.impact-north-america.com/',
          facebook:'https://www.facebook.com/impactusa18/',
          twitter:'https://twitter.com/usa_impact',
          linkedin:'https://www.linkedin.com/company/impact-usa/'
        },
        { id: 33, 
          label: '360learning',
          name: '360 LearninG', 
          description: 'The vision we have at 360Learning is simple: re-think e-learning and make digital training an uplifting collective adventure', 
          image:'https://pbs.twimg.com/profile_images/936183255036022784/yeWIJpKN_400x400.jpg',
          website:'https://360learning.com/',
          facebook:'https://www.facebook.com/360learningFR/',
          twitter:'https://twitter.com/360learning',
          linkedin:'https://www.linkedin.com/company/360learning/'
        },
        { id: 34, 
          label: 'splio',
          name: 'Splio', 
          description: 'The Splio customer platform drives connected loyalty marketing on and offline delivering revenue and profit across every channel.', 
          image:'https://pbs.twimg.com/profile_images/963310001480749056/FNDiFLxM_400x400.jpg',
          website:'https://www.splio.com/',
          facebook:'https://www.facebook.com/spliogroup',
          twitter:'https://twitter.com/Splio',
          linkedin:'https://www.linkedin.com/company/splio/'
        },
        { id: 35, 
          label: 'simplifield',
          name: 'SimpliField', 
          description: 'SimpliField empowers companies to connect with their field team, create smarter execution processes and improve their performance with more predictive decisions from anywhere, in real time. We tear down silos between services and make sure everyone is on board and aligned to reach the level of excellence expected by customers.', 
          image:'https://pbs.twimg.com/profile_images/955851898623614976/ChCpMyqc_400x400.jpg',
          website:'https://www.simplifield.com/',
          facebook:'https://www.facebook.com/simplifield/',
          twitter:'https://twitter.com/simplifield',
          linkedin:'https://www.linkedin.com/company/simplifield/'
        },
        { id: 36, 
          label: 'syntony',
          name: 'Syntony Gnss', 
          description: 'Syntony GNSS is a young High Tech Company. Our core competence is advanced Software based Location and Navigation Systems adapted to our customers needs.', 
          image:'https://pbs.twimg.com/profile_images/761499076898725888/s6hX-oX2_400x400.jpg',
          website:'http://syntony-gnss.com/',
          facebook:'https://www.facebook.com/SyntonyGNSS/',
          twitter:'https://twitter.com/Syntony_GNSS',
          linkedin:'https://www.linkedin.com/company/syntony-gnss/'
        },
        { id: 37, 
          label: 'vize',
          name: 'Vize', 
          description: 'Vize is an agile data experimentation tool. It helps you prepare and analyze data on-the-fly without coding, with real-time visual feedback on every action.', 
          image:'https://pbs.twimg.com/profile_images/782837276816670720/X_u-LZ75_400x400.jpg',
          website:'http://vize.io/',
          facebook:'',
          twitter:'https://twitter.com/VizeSoftware',
          linkedin:'https://www.linkedin.com/company/vize/'
        },
        { id: 38, 
          label: 'woleet',
          name: 'Woleet', 
          description: 'Woleet is a digital notary solution, based on the Bitcoin blockchain. We enable you to certify & register your data with an unrivalled level of security at an affordable price.', 
          image:'https://pbs.twimg.com/profile_images/745284432219750400/FO6Hd5Ow_400x400.jpg',
          website:'https://www.woleet.io/en',
          facebook:'https://www.facebook.com/Woleet/',
          twitter:'https://twitter.com/Woleet',
          linkedin:'https://www.linkedin.com/company/woleet/'
        },
        { id: 39, 
          label: 'mibi',
          name: 'Mibi', 
          description: 'Mibi is a tech platform for audience engagement and monetization through digital challenges and gamification. Our white-label solutions are integrated into the digital properties of our partners, including leading sports, media and entertainment enterprises.', 
          image:'https://pbs.twimg.com/profile_images/643257848198119424/PyIIj7eQ_400x400.png',
          website:'http://mibi.com/',
          facebook:'https://www.facebook.com/mibiapp/',
          twitter:'https://twitter.com/mibiapp',
          linkedin:'https://www.linkedin.com/company/mibi-inc-/'
        },
        { id: 40, 
          label: 'arlohotels',
          name: 'Arlo Hotels', 
          description: 'Arlo is committed to being a great place to work, providing exceptional service for our guests through our unique approach to the independent lifestyle hotel segment.', 
          image:'https://pbs.twimg.com/profile_images/925039771591753729/-Bw_UIp-_400x400.jpg',
          website:'https://www.arlohotels.com/',
          facebook:'https://www.facebook.com/ArloHotelSoHo',
          twitter:'https://twitter.com/arlohotels',
          linkedin:'https://www.linkedin.com/company/arlo-hotel-group/'
        },
        { id: 41, 
          label: 'launchcapital',
          name: 'Launch Capital', 
          description: 'LaunchCapital provides seed funding for startups that have exponential growth expectations. We syndicate over 90% of our deals with local angel investors and venture capitalists. We will take on an active role with our portfolio companies depending on the needs and nature of the business.', 
          image:'https://pbs.twimg.com/profile_images/892054683174543362/OLLdc_RG_400x400.jpg',
          website:'https://launchcapital.com/',
          facebook:'',
          twitter:'https://twitter.com/launchcapital',
          linkedin:'https://www.linkedin.com/company/launchcapital-llc/'
        },
        { id: 42, 
          label: 'dopamine',
          name: 'Dopamine', 
          description: 'Dopamine is a creative agency headed by one of the world\'s foremost gamification experts, Gabe Zichermann. Through innovative game design, time tested gamification strategy, and an agile, iterative development process, Dopamine produces memorable, engaging, and effective game experiences.', 
          image:'https://pbs.twimg.com/profile_images/3480849707/a409e04433cdb6200e73465b40591082_400x400.png',
          website:'http://dopa.mn/',
          facebook:'',
          twitter:'https://twitter.com/dopamine',
          linkedin:'https://www.linkedin.com/company/dopamine/'
        },
        { id: 43, 
          label: 'munichre',
          name: 'Munich Re', 
          description: 'Munich Re is one of the world’s leading risk carriers and stands for exceptional solution-based expertise, consistent risk management, financial stability and client proximity. The Group operates in all lines of insurance, with around 45,000 employees throughout the world and combines primary insurance and reinsurance under one roof.', 
          image:'https://pbs.twimg.com/profile_images/660110621355188224/Bcph4r16_400x400.png',
          website:'https://www.munichre.com/en/homepage/index.html',
          facebook:'https://www.facebook.com/munichre/',
          twitter:'https://twitter.com/MunichRe',
          linkedin:'https://www.linkedin.com/company/munich-re/'
        },
      ]);
    });
};
